[package]
name = "actix-web-responsable"
version = "0.1.0"
authors = ["lsunsi <sunsi.lucas@gmail.com>", "FelipeRosa <felipe.sgrosa@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3"
actix-web = "3"
anyhow = "1"
quote = "1"
syn = "1"

[lib]
proc-macro = true
